# ---------------------------------------------------------------------------- #
#                             EXPERIMENT FILE PATHS                            #
# ---------------------------------------------------------------------------- #
overwrite_files: True  # ! If true OVERWRITING EXISTING FILES
base_dir: E:\test   # this shouldn't change that often
exp_dir: 191202_test # this is specific to each experiment


# ---------------------------------------------------------------------------- #
#                              EXPERIMENT METADATA                             #
# ---------------------------------------------------------------------------- #
n_recording_sites: 1
single_fiber_diameter: 275  # diameter in pixels of one fiber on the frame
single_fiber_radius_titration: 25 # remove N pixels from the radius of ROIs to be more conservative
detect_fibers_manual: False # if false automatic detection is attempted, but this doesn't work very well at the moment
fast_signal_extraction: True # If True a faster but less sensitive method for signal extraction is used

# ---------------------------------------------------------------------------- #
#                             VISUALIZATION CONFIG                             #
# ---------------------------------------------------------------------------- #
visual_config:
    n_display_points: 200

# ---------------------------------------------------------------------------- #
#                             SAVE TO VIDEO PARAMS                             #
# ---------------------------------------------------------------------------- #
save_to_video: True # If false it only streams the video but doesn't save it
output_fps: 20


# ---------------------------------------------------------------------------- #
#                                NI BOARD PARAMS                               #
# ---------------------------------------------------------------------------- #
niboard_config:
    ni_device: "Dev3"
    blue_led_trigger_port: '0'
    blue_led_trigger_line: '2'
    violet_led_trigger_port: '0'
    violet_led_trigger_line: '3'
    camera_trigger_port: '0'
    camera_trigger_line: '0'


# ---------------------------------------------------------------------------- #
#                                 CAMERA CONFIG                                #
# ---------------------------------------------------------------------------- #
camera_config:
    video_format: .avi
    n_cameras: 1
    timeout: 100   # frame acquisition timeout

    # Trigger mode and acquisition options -> needed for constant framerate
    trigger_mode: True  # ! hardware triggering
    acquisition:     # ||| change this parameters to set up camera acquisition as required
        exposure: "5000"
        frame_width: "768"  # must be a multiple of 32
        frame_height: "768" # must be a multiple of 32
        gain: "12"
        frame_offset_y: "192" # must be a multiple of 32
        frame_offset_x: "576" # must be a multiple of 32
    
    outputdict: # for ffmpeg
        -c:v: 'libx264'   #   low fps high res
        -crf: '17'
        -preset: 'ultrafast'
        -pix_fmt: 'yuv444p'

